text_offset = 0x68020
text_size = 0xC60
text_address = 0x04001000
rom_file_path = "baserom.z64"
output_file_path = "rsp/aspMain.cpp"
output_function_name = "aspMain"
extra_indirect_branch_targets = [
    0x10EC,
]
